### ISSUE TITLE
Release SDK v1.2.0

### ISSUE THREAD

**Issue by marclop** [elastic/cloud-sdk-go#280]
## Overview

ECE 2.8.0 is scheduled for Tuesday the 9th, we should release the SDK accordingly.

- [x] Merge #279 
- [x] Generate release notes #287.
- [x] Cut a 1.2.0 branch 
- [x] Bump the master version to `v1.3.0` and ECE version to `2.9.0` #285.
- [x] Update the `apidocs.json` and `apidocs-user.json` from the MS-53 branch #285.
